# Generated by Django 4.2.5 on 2023-09-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_orderitem_shipping_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("P", "pending"), ("C", "completed"), ("L", "placed")],
                default="P",
                max_length=1,
            ),
        ),
    ]
