# Generated by Django 4.2.5 on 2023-09-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ref",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
