#!/bin/bash

set -o errexit

set -o nounset

# watchdog ensures workers start automatically- resolves autoreloading issue
watchmedo auto-restart -d ecommerce/ -p "*.py" -- celery -A ecommerce worker --loglevel=info
