version: "3.3"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - postgres-db
            - redis
        networks:
            - ecommerce
    postgres-db:
        image: postgres:12.0-alpine
        ports:
            - "5431:5431"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - ecommerce

    redis:
        image: redis:5-alpine
        networks:
            - ecommerce

    # celery_worker:
    #     build:
    #         context: .
    #         dockerfile: ./docker/local/django/Dockerfile
    #     command: /start-celeryworker
    #     volumes:
    #         - .:/app
    #     env_file:
    #         - .env
    #     depends_on:
    #         - redis
    #         - postgres-db
    #     networks:
    #         - ecommerce

    # flower:
    #     build:
    #         context: .
    #         dockerfile: ./docker/local/django/Dockerfile
    #     command: /start-flower
    #     volumes:
    #         - .:/app
    #     env_file:
    #         - .env
    #     ports:
    #         - "5557:5555"
    #     depends_on:
    #         - redis
    #         - postgres-db
    #     networks:
    #         - ecommerce

networks:
    ecommerce:
        driver: bridge

volumes:
    postgres_data:
    static_volume:
    media_volume:
