# Generated by Django 4.2.5 on 2023-09-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
