# Generated by Django 4.2.5 on 2023-09-16 06:08

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_otp_user_otp_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+254799757242",
                max_length=30,
                region=None,
                verbose_name="Phone number",
            ),
        ),
    ]
