name: Run Tests on Ecommerce API

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transfer .env File
        run: |
          scp ${{ secrets.ECOM_USERNAME }}@${{ secrets.ECOM_HOSTNAME }}:~/.env .env

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run Tests
        run: |
          source .env  # Load environment variables from the transferred .env file
          docker-compose exec api pytest -p no:warnings --cov=.

      - name: Remove .env File
        run: rm .env  # Remove the .env file after it's done being used
